language: node_js
node_js:
  - "0.11"
  - "0.12"
  - "iojs"
script: "npm run-script test-travis"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
